# This is a basic workflow to help you get started with Actions

name: vietsub_build

on:
  workflow_dispatch:
  watch:
    types: [started]
    
env:              
  ROM_URL: 'https://bigota.d.miui.com/21.11.17/miui_BEGONIA_21.11.17_c05ad0fe41_11.0.zip'
  Zip_name: 'MIUI_VietSub_BEGONIA_21.11.17_c05ad0fe41_11.0.zip'
  USERNAME: buihien224@gmail.com
  PASSWORD: hienhien
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@main
       
       - name: Clean Up
         run: |       
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean
           df -h
           
       - name: Setting up the SPICES
         run: |
            sudo apt-get install -y git wget git zip unzip img2simg
       - name: Cloning...
         run: |
             git clone -b action https://github.com/buihien224/MIUI_VIETSUB.git $GITHUB_WORKSPACE/MIUI_VIETSUB
           
       - name: Download zip... and run
         run: |
            cd $GITHUB_WORKSPACE/MIUI_VIETSUB
            chmod +x download.sh
            chmod +x bhlnk.sh
            sudo bash download.sh $ROM_URL 
            mv MIUI_VIETSUB.zip $Zip_name
       - name: Upload to mega
         uses: Difegue/action-megacmd@master
         with:
          args: put $GITHUB_WORKSPACE/MIUI_VIETSUB/$Zip_name /MIUI_VIETSUB/
